name: sf-env
channels:
 - snowflake
dependencies:
 - python=3.11
 # Core
 - streamlit=1.35.0
 - streamlit-extras=0.4.0
 # Data
 - pandas=2.2.2
 - numpy=1.26.4
 - pyarrow=14.0.2
 # Snowflake (CRITICAL PART)
 - snowflake-snowpark-python=1.18.0
 - snowflake-connector-python[pandas]
 # Serialization / config
 - pyyaml=6.0.1
 - ruamel.yaml=0.17.21
 - protobuf=3.20.3
 # Validation & utils
 - pydantic=2.8.2
 - tqdm=4.66.5
 - loguru=0.5.3
 - sqlglot=25.10.0
 - python-dotenv=0.21.0
 - requests=2.32.3
 - urllib3=2.2.2
 - cattrs=23.1.2
