[project]
name = "semantic-model-generator-app"
version = "0.1.0"
dependencies = [
  "streamlit>=1.50.0",
  "strictyaml>=1.7.3",
  "ruamel.yaml==0.17.21",
  "snowflake-snowpark-python>=1.10.0",
  "snowflake-connector-python>=3.0.0",
  "sqlglot==25.10.0"
]
